#!/usr/bin/env bash
set -euo pipefail

cd "${CYBERRUNNER_ROOT:-$HOME/cyberruner-main}"
set +u
. install/setup.bash
set -u

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-1,2}"
export CYBERRUNNER_DREAMER4_ENTRY="${CYBERRUNNER_DREAMER4_ENTRY:-dreamer4.train:main}"
export CYBERRUNNER_DREAMER4_POLICY_DEVICES="${CYBERRUNNER_DREAMER4_POLICY_DEVICES:-0}"
export CYBERRUNNER_DREAMER4_TRAIN_DEVICES="${CYBERRUNNER_DREAMER4_TRAIN_DEVICES:-0 1}"
export CYBERRUNNER_DREAMER4_SCRIPT="${CYBERRUNNER_DREAMER4_SCRIPT:-train}"
export CYBERRUNNER_DREAMER4_TRAIN_RATIO="${CYBERRUNNER_DREAMER4_TRAIN_RATIO:-128}"
export CYBERRUNNER_TCP_BIND="${CYBERRUNNER_TCP_BIND:-127.0.0.1}"
export CYBERRUNNER_TCP_PORT="${CYBERRUNNER_TCP_PORT:-5555}"

stamp="$(date +%Y%m%d_%H%M%S)"
export CYBERRUNNER_THOMAS_DREAMER4_LOGDIR="${CYBERRUNNER_THOMAS_DREAMER4_LOGDIR:-$HOME/cyberrunner_logs/thomas_dreamer4_tcp_gpu12_$stamp}"

echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
echo "CYBERRUNNER_DREAMER4_ENTRY=$CYBERRUNNER_DREAMER4_ENTRY"
echo "CYBERRUNNER_THOMAS_DREAMER4_LOGDIR=$CYBERRUNNER_THOMAS_DREAMER4_LOGDIR"
echo "TCP bind: $CYBERRUNNER_TCP_BIND:$CYBERRUNNER_TCP_PORT"

ros2 run cyberrunner_dreamer_thomas train_tcp_dreamer4_thomas
