#!/usr/bin/env python3
"""Validate TAG maze geometry and build reviewable artifacts."""

import argparse
import json
import math
import pprint
import sys
from pathlib import Path


REQUIRED_KEYS = {
    "schema_version",
    "maze_id",
    "units",
    "board_width",
    "board_height",
    "ball_radius",
    "wall_thickness",
    "wall_height",
    "walls_h",
    "walls_v",
    "walls_angled",
    "holes",
    "hole_radii",
    "waypoints",
}


def finite_number(value, label):
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{label} must be a number")
    value = float(value)
    if not math.isfinite(value):
        raise ValueError(f"{label} must be finite")
    return value


def point_in_bounds(x, y, width, height, label):
    x = finite_number(x, f"{label}.x")
    y = finite_number(y, f"{label}.y")
    if not 0.0 <= x <= width or not 0.0 <= y <= height:
        raise ValueError(
            f"{label} ({x}, {y}) is outside board {width} x {height} m"
        )
    return x, y


def validate(raw):
    missing = sorted(REQUIRED_KEYS - raw.keys())
    if missing:
        raise ValueError("missing keys: " + ", ".join(missing))
    if raw["schema_version"] != 1:
        raise ValueError("only schema_version 1 is supported")
    if raw["units"] != "meters":
        raise ValueError("units must be 'meters'")
    if not str(raw["maze_id"]).strip():
        raise ValueError("maze_id must not be empty")

    width = finite_number(raw["board_width"], "board_width")
    height = finite_number(raw["board_height"], "board_height")
    ball_radius = finite_number(raw["ball_radius"], "ball_radius")
    wall_thickness = finite_number(raw["wall_thickness"], "wall_thickness")
    wall_height = finite_number(raw["wall_height"], "wall_height")
    if min(width, height, ball_radius, wall_thickness, wall_height) <= 0.0:
        raise ValueError(
            "board dimensions, ball radius, wall thickness, and wall height must be positive"
        )

    for index, wall in enumerate(raw["walls_h"]):
        if len(wall) != 3:
            raise ValueError(f"walls_h[{index}] must be [start_x, end_x, y]")
        start, end, y = map(float, wall)
        point_in_bounds(start, y, width, height, f"walls_h[{index}].start")
        point_in_bounds(end, y, width, height, f"walls_h[{index}].end")
        if end <= start:
            raise ValueError(f"walls_h[{index}] end must be greater than start")

    for index, wall in enumerate(raw["walls_v"]):
        if len(wall) != 3:
            raise ValueError(f"walls_v[{index}] must be [start_y, end_y, x]")
        start, end, x = map(float, wall)
        point_in_bounds(x, start, width, height, f"walls_v[{index}].start")
        point_in_bounds(x, end, width, height, f"walls_v[{index}].end")
        if end <= start:
            raise ValueError(f"walls_v[{index}] end must be greater than start")

    for index, wall in enumerate(raw["walls_angled"]):
        if len(wall) != 4:
            raise ValueError(
                f"walls_angled[{index}] must be [start_x, start_y, end_x, end_y]"
            )
        x1, y1, x2, y2 = map(float, wall)
        point_in_bounds(x1, y1, width, height, f"walls_angled[{index}].start")
        point_in_bounds(x2, y2, width, height, f"walls_angled[{index}].end")
        if x1 == x2 and y1 == y2:
            raise ValueError(f"walls_angled[{index}] has zero length")

    if len(raw["holes"]) != len(raw["hole_radii"]):
        raise ValueError("holes and hole_radii must contain the same number of entries")
    for index, (hole, radius) in enumerate(zip(raw["holes"], raw["hole_radii"])):
        if len(hole) != 2:
            raise ValueError(f"holes[{index}] must be [x, y]")
        x, y = point_in_bounds(*hole, width, height, f"holes[{index}]")
        radius = finite_number(radius, f"hole_radii[{index}]")
        if radius <= 0.0:
            raise ValueError(f"hole_radii[{index}] must be positive")
        if x - radius < 0 or x + radius > width or y - radius < 0 or y + radius > height:
            raise ValueError(f"holes[{index}] extends outside the board")

    if len(raw["waypoints"]) < 2:
        raise ValueError("at least two ordered waypoints are required")
    for index, point in enumerate(raw["waypoints"]):
        if len(point) != 2:
            raise ValueError(f"waypoints[{index}] must be [x, y]")
        point_in_bounds(*point, width, height, f"waypoints[{index}]")

    normalized = dict(raw)
    normalized["board_width"] = width
    normalized["board_height"] = height
    normalized["ball_radius"] = ball_radius
    normalized["wall_thickness"] = wall_thickness
    normalized["wall_height"] = wall_height
    return normalized


def write_python(layout, destination):
    content = (
        "# Generated by tools/maze/build_maze.py; do not edit manually.\n"
        + "tag_layout = "
        + pprint.pformat(layout, sort_dicts=False, width=100)
        + "\n"
    )
    destination.write_text(content, encoding="utf-8")


def write_svg(layout, destination):
    scale = 1000.0
    width = layout["board_width"]
    height = layout["board_height"]
    stroke = layout["wall_thickness"] * scale

    def sx(x):
        return float(x) * scale

    def sy(y):
        return (height - float(y)) * scale

    elements = [
        f'<rect x="0" y="0" width="{sx(width):.3f}" height="{sx(height):.3f}" '
        'fill="white" stroke="black" stroke-width="2"/>'
    ]
    for x1, x2, y in layout["walls_h"]:
        elements.append(
            f'<line x1="{sx(x1):.3f}" y1="{sy(y):.3f}" x2="{sx(x2):.3f}" '
            f'y2="{sy(y):.3f}" stroke="black" stroke-width="{stroke:.3f}"/>'
        )
    for y1, y2, x in layout["walls_v"]:
        elements.append(
            f'<line x1="{sx(x):.3f}" y1="{sy(y1):.3f}" x2="{sx(x):.3f}" '
            f'y2="{sy(y2):.3f}" stroke="black" stroke-width="{stroke:.3f}"/>'
        )
    for x1, y1, x2, y2 in layout["walls_angled"]:
        elements.append(
            f'<line x1="{sx(x1):.3f}" y1="{sy(y1):.3f}" x2="{sx(x2):.3f}" '
            f'y2="{sy(y2):.3f}" stroke="black" stroke-width="{stroke:.3f}"/>'
        )
    for (x, y), radius in zip(layout["holes"], layout["hole_radii"]):
        elements.append(
            f'<circle cx="{sx(x):.3f}" cy="{sy(y):.3f}" r="{sx(radius):.3f}" '
            'fill="#d62728" fill-opacity="0.6"/>'
        )
    points = " ".join(f"{sx(x):.3f},{sy(y):.3f}" for x, y in layout["waypoints"])
    elements.append(f'<polyline points="{points}" fill="none" stroke="#1f77b4" stroke-width="1.5"/>')
    start_x, start_y = layout["waypoints"][0]
    end_x, end_y = layout["waypoints"][-1]
    elements.append(f'<circle cx="{sx(start_x):.3f}" cy="{sy(start_y):.3f}" r="3" fill="green"/>')
    elements.append(f'<circle cx="{sx(end_x):.3f}" cy="{sy(end_y):.3f}" r="3" fill="blue"/>')
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {sx(width):.3f} {sx(height):.3f}">\n'
        + "\n".join(elements)
        + "\n</svg>\n"
    )
    destination.write_text(svg, encoding="utf-8")


def write_path_pickle(layout, destination, repository_root):
    if layout["walls_angled"]:
        raise ValueError(
            "path pickle generation does not support angled-wall collision checks; "
            "refusing to generate an unsafe map"
        )
    if any(abs(float(radius) - 0.0075) > 1e-9 for radius in layout["hole_radii"]):
        raise ValueError(
            "the current LinearPath implementation assumes 0.0075 m hole radii; "
            "refusing to generate a mismatched path pickle"
        )
    sys.path.insert(0, str(repository_root))
    import numpy as np
    from tag_dreamer.tag_dreamer.path import LinearPath

    path = LinearPath(
        np.asarray(layout["waypoints"], dtype=np.float32),
        walls_h=np.asarray(layout["walls_h"], dtype=np.float32).reshape((-1, 3)),
        walls_v=np.asarray(layout["walls_v"], dtype=np.float32).reshape((-1, 3)),
        holes=np.asarray(layout["holes"], dtype=np.float32).reshape((-1, 2)),
        board_width=layout["board_width"],
        board_height=layout["board_height"],
        wall_r=layout["wall_thickness"] / 2.0,
    )
    path.save(destination)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("maze", type=Path, help="versioned maze.json")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--path-pickle",
        action="store_true",
        help="also generate path_custom.pkl when geometry is supported",
    )
    parser.add_argument(
        "--print-package",
        action="store_true",
        help="also export the common MJCF/PNG/route/prototype-STL package",
    )
    args = parser.parse_args()

    layout = validate(json.loads(args.maze.read_text(encoding="utf-8")))
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "manifest.json").write_text(
        json.dumps(layout, indent=2) + "\n", encoding="utf-8"
    )
    write_python(layout, args.output_dir / "layout_generated.py")
    write_svg(layout, args.output_dir / "maze_preview.svg")
    if args.path_pickle:
        repository_root = Path(__file__).resolve().parents[2]
        write_path_pickle(layout, args.output_dir / "path_custom.pkl", repository_root)
    if args.print_package:
        repository_root = Path(__file__).resolve().parents[2]
        sys.path.insert(0, str(repository_root))
        from tag_mujoco.maze_artifact import export_maze_artifact

        export_maze_artifact(args.maze, args.output_dir / "package")
    print(f"Validated {layout['maze_id']} and wrote artifacts to {args.output_dir}")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        raise SystemExit(f"maze generation failed: {exc}") from exc
